title: sudomaze
description: >
  ...
baseurl: ""
url: "https://sudomaze.dev"
repository: "sudomaze/sudomaze.github.io"

encoding: "utf-8"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-last-modified-at

include: ['_pages', '_notes', '_about']

head_links:
  - /assets/libraries/bootstrap-4.3.1-dist/css/bootstrap.min.css
  - /assets/libraries/katex/katex.min.css
  - /assets/libraries/pseudocode.js-1.1/pseudocode.css
  - /assets/css/styles.css

head_scripts:
  - /assets/libraries/katex/katex.min.js
  - /assets/libraries/pseudocode.js-1.1/pseudocode.js


footer_scripts:
  - /assets/libraries/jquery-3.4.1/jquery-3.4.1.min.js
  - /assets/libraries/bootstrap-4.3.1-dist/js/bootstrap.min.js
  - /assets/js/index.js